import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import './style/tailwind.css';
import './style/global.css';
import { registerGlobalComponent } from './utils/import';
import store from './store';
const app = createApp(App);
registerGlobalComponent(app);
app.use(router);
app.use(store);
app.mount('#app');
